### ISSUE TITLE
Shell doesnt work

### ISSUE THREAD

**Issue by SkyBlockDev** [MoltenCoreDev/noOS#8]
it only lets me type one letter

**Comment by SkyBlockDev** [comment]
![image](https://user-images.githubusercontent.com/72335827/105640068-4fa37480-5e7c-11eb-85f7-b4e319d43941.png)

**Comment by mugman174** [comment]
That's as far as we've gone so far. If you'd like to help us with multi-chraracter input, that'd help.

**Comment by MoltenCoreDev** [comment]
basiclly im too small brain for it so for now commands are 1 letter long, defintly gonna add more then one letter support soon.

**Comment by mugman174** [comment]
We've put a feature in testing.
at the `[Power Shell] >> ` prompt, type `s`. All letters you type after that will be printed on screen. It goes to next line (exits single-line mode) when you type a `.`. Backspaces and some other keys (usually key combos) print random unicode chars so beware.

**Comment by MoltenCoreDev** [comment]
Done with gliches on unstable branch.

**Comment by mugman174** [comment]
🎉 COMPLETED in MASTER BRANCH 🎉 
Check the `h` or `.help` command for more info.
